# Generated by Django 4.0.3 on 2022-06-20 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('productName', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('MRP', models.DecimalField(decimal_places=4, max_digits=8)),
                ('SP', models.DecimalField(decimal_places=4, max_digits=8)),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('productName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='warehouse.product')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('productName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='warehouse.product')),
                ('quantity', models.IntegerField()),
                ('pinCode', models.IntegerField()),
                ('deliveryTime', models.DateTimeField()),
            ],
        ),
    ]
